try:
    try:
        from ._dev_version import __version__
    except ImportError:
        from ._version import __version__
except Exception:
    import warnings

    warnings.warn(
            "Could not determine lstmcpipe version; this indicates a broken installation."
            "Install lstmcpipe from PyPI, or from a local git repository."
            "Installing github's autogenerated source release tarballs "
            "does not include version information and should be avoided."
        )

    __version__ = '0.0.0'
