name: RsMetaCheck Validation

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  analyze-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Run RsMetaCheck
        uses: SoftwareUnderstanding/rs-metacheck-action@0.3.1
        with:
          # You can pass the repository URL automatically
          input: "https://github.com/${{ github.repository }}"
          pitfalls_output: "./pitfalls_outputs"
          verbose: "false"